config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pise.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pise/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home_view, name='index'),
    path('accounts/login/', views.UserLoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    #Establecimiento
    path('ajustes/<int:pk>', views.EstablecimientoUsuarioDetailView.as_view(),name='detail'),
    path('ajustes/<int:pk>/actualizar',views.EstablecimientoUsuarioUpdateView.as_view(),name='update'),
    #Alumnos
    path('matriculas/', views.MatriculaEstablecimientoListView.as_view(), name='matriculas'),
    path('matricula/<int:pk>', views.MatriculaEstablecimientoDetailView.as_view(), name='matricula_detail'),
    path('matricula/<int:pk>/actualizar',views.MatriculaEstablecimientoUpdateView.as_view(), name='matricula_edit' ),
    path('matriculas/crear', views.CargarNominaMatriculas, name='matriculas_create'),
    path('matriculas/inscribir', views.MatriculaEstablecimientoCreateView.as_view(), name='matriculas_add'),
    #Funcionarios
    path('funcionarios/', views.FuncionarioEstablecimientoListView.as_view(), name='funcionarios'),
    path('funcionario/<int:pk>', views.FuncionarioEstablecimientoDetailView.as_view(), name='funcionario_detail'),
    path('funcionario/<int:pk>/actualizar',views.FuncionarioEstablecimientoUpdateView.as_view(), name='funcionario_edit' ),
    path('funcionario/crear', views.FuncionarioEstablecimientoCreateView.as_view(), name='funcionario_add'),
    #CASOS
    path('caso/', views.CasoCreateView.as_view(), name='create_caso'),
    path('caso/<int:pk>/update', views.CasoUpdateView.as_view(), name='update_caso'),
    # CRUD DISCRIMINACION

    path('casos_discriminacion', views.DiscriminacionListView.as_view(), name='discriminacion_list'),
    path('caso_discriminacion/crear', views.DiscriminacionCreateView.as_view(), name='discriminacion_add'),
    path('discriminacion/<int:pk>', views.DiscriminacionDetailView.as_view(), name='discriminacion_detail'),
    # path('discriminacion/crear', views.DiscriminacionCreateView.as_view(), name='discriminacion_add'),
    # MEDIDAS DISCRIMINACION
    path('discriminacion/<int:pk>/medidas', views.medidas_discriminacion_view, name='discriminacion_medidas'),
    path('discriminacion/<int:pk>/medidas/actualizar', views.actualizar_medidas_discriminacion, name='actualizar_discriminacion_medidas'),
    path('caso_discriminacion/<int:pk>/update', views.DiscriminacionUpdateView.as_view(), name='discriminacion_update'),

    # CRUD Maltrato
    #path('caso_maltrato/', views.CasoMaltratoCreateView.as_view(), name='create_caso_maltrato'),
    path('caso_maltrato/crear', views.MaltratoCreateView.as_view(), name='maltrato_add'),
    path('caso_maltrato/crear/menor_a_menor', views.MaltratoAlumnoToAlumnoCreateView.as_view(), name='maltrato_alumnotoalumno_add'),
    path('caso_maltrato/crear/adulto_a_menor', views.MaltratoFuncionarioToAlumnoCreateView.as_view(), name='maltrato_funcionariotoalumno_add'),
    path('caso_maltrato/crear/adulto_a_adulto', views.MaltratoAdultoToAdultoCreateView.as_view(), name='maltrato_adultotoadulto_add'),
    path('caso_maltrato/crear/funcionario_a_alumno', views.MaltratoFuncionarioToAlumnoCreateView.as_view(), name='maltrato_funcionariotoalumno_add'),

    path('caso_maltrato/<int:pk>', views.MaltratoDetailView.as_view(), name='maltrato_detail'),
    path('casos_maltrato/', views.MaltratoListView.as_view(), name='maltrato_list'),
    path('caso_maltrato/<int:pk>/actualizar', views.MaltratoUpdateView.as_view(), name='maltrato_update'),
    #path('caso_maltrato/<int:pk>/medidas', views.MedidasMaltratoView.as_view(), name='maltrato_medidas'),
    path('caso_maltrato/<int:pk>/medidas/crear', views.medidas_maltrato_view, name='add_maltrato_medidas'),
    path('caso_maltrato/<int:pk>/medidas/update', views.actualizar_medidas_maltratos, name='actualizar_maltrato_medidas'),


    # CRUD Connotacion
    path('caso_connotacion/crear', views.FullConnotacionSexualCreateView.as_view(), name='create_caso_connotacion'),
    path('casos_connotacion/', views.ConnotacionSexualListView.as_view(), name='connotacion_list'),
    #path('caso_connotacion/<int:pk>/connotacion/crear/', views.ConnotacionSexualCreateView.as_view(), name='connotacion_add'),
    path('caso_connotacion/<int:pk>', views.ConnotacionSexualDetailView.as_view(), name='connotacion_detail'),
    path('caso_connotacion/<int:pk>/update', views.ConnotacionSexualUpdateView.as_view(), name='connotacion_update'),

    #CRUD ACCIDENTE_ESCOLAR

    path('caso_accidente/create', views.AccidenteEscolarCreateView.as_view(), name='add_accidente'),
    path('caso_accidente/<int:pk>', views.AccidenteEscolarDetailView.as_view(), name='detail_accidente'),
    path('caso_accidente/<int:pk>/actualizar', views.AccidenteEscolarUpdateView.as_view(), name='update_accidente'),
    path('caso_accidente/<int:pk>/actualizar_estado', views.AccidenteEscolarEstadoUpdateView.as_view(), name='update_estado_accidente'),
    path('casos_accidente/', views.AccidenteEscolarListView.as_view(), name='list_accidente'),

    #CRUD DIFICULTAD CONSEJOS
    path('caso_consejo/create', views.DificultadConstitucionCreateView.as_view(), name='add_dificultad'),
    path('caso_consejo/<int:pk>', views.DificultadConstitucionDetailView.as_view(), name='detail_dificultad'),
    path('caso_consejos/', views.DificultadConstitucionListView.as_view(), name='list_dificultad'),
    path('caso_consejo/<int:pk>/actualizar_estado', views.DificultadConsejoEstadoUpdateView.as_view(), name='update_status_dificultad'),

    #CRUD VULNERACION DERECHOS FUNCIONARIOS
    path('caso_vulneracion_funcionarios/create', views.VulneracionDerechosFuncionariosCreateView.as_view(), name='add_vulneracion_funcionario'),
    path('casos_vulneraciones_funcionarios/', views.VulneracionDerechosFuncionariosListView.as_view(), name='list_vulneracion_funcionario'),
    path('caso_vulneracion_funcionarios/<int:pk>', views.VulneracionDerechosFuncionariosDetailView.as_view(), name='detail_vulneracion_funcionario'),
    path('caso_vulneracion_funcionarios/<int:pk>/actualizar_estado', views.VulneracionFuncionariosEstadoUpdateView.as_view(), name='update_status_vulneracion_funcionario'),

    #descarga_archivo_accidente_escolar
    path('descargar_dec/', views.descarga_archivo_accidente_escolar, name='download_dec'),
    path('reportes/', views.ReportesView.as_view(), name='reportes'),

    #Creación de PDF
    path('reporte_maltrato/<int:pk>', views.report_vulneracion, name='reporte-vulneracion'),
    path('report_discriminacion/<int:pk>', views.report_discriminacion, name='reporte-discrim'),
    path('report_connotacion/<int:pk>', views.report_connotacionsexual, name='reporte-connotacion'),
    path('report_dificultad_consejo_escolar/<int:pk>', views.report_dificultad_consejo_escolar, name='reporte-dificultad'),
    path('report_vulneracion_derechos_funcionarios/<int:pk>', views.report_vulneracion_derechos_funcionario, name='reporte-vulneracion-funcionarios'),

    #CRUD Alumno
    #path('matriculas/Agregar', views.MatriculaCreateView.as_view(), name='add_alumn'),

    path('protocolos/<str:tipo>/upload/', views.ProtocoloUploadView.as_view(), name='protocolo_upload'),
    path('protocolos/<str:tipo>/list/', views.ProtocoloListView.as_view(), name='protocolo_list'),

] 

pise/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ManyToManyField
from django.urls import reverse 

# Create your models here.
'''
class Alumno(models.Model):
    rut = models.IntegerField()
    dv = models.CharField(max_length=1, blank=True, null=True)
    nombres = models.CharField(max_length=255, blank=True, null=True)
    apellido_paterno = models.CharField(max_length=255, blank=True, null=True)
    apellido_materno = models.CharField(max_length=255, blank=True, null=True)
    nombre_apoderado = models.CharField(max_length=255, blank=True, null=True)
    domicilio_actual = models.CharField(max_length=255, blank=True, null=True)
    Comuna_residencia = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    telefono = models.CharField(max_length=255, blank=True, null=True)
    celular = models.CharField(max_length=255, blank=True, null=True)
    fecha_nacimiento = models.DateField(auto_now=False, blank=True, null=True)
    codigo_etnia = models.IntegerField()

    def __str__(self) -> str:
        return f'{self.nombre} {self.apellido}'
'''
class Establecimiento(models.Model):
    usuario = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    nombre = models.CharField(max_length=255, blank=True, null=True)
    rbd = models.CharField(max_length=6, blank=True, null=True, unique=True)
    telefono = models.IntegerField(blank=True, null=True)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    logo = models.ImageField(upload_to='logo_colegio/', blank=True, null=True)
    reglamento_interno = models.FileField(upload_to='reglamento/', blank=True, null=True)
    nombramiento_encargado_convivencia = models.FileField(upload_to='nombramiento_encargado_convivencia/', blank=True, null=True)
    plan_gestion_convivencia = models.FileField(upload_to='plan_gestion_convivencia/', blank=True, null=True)
    

    def __str__(self) -> str:
        return f'{self.rbd} {self.nombre}'

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])


class Matricula(models.Model):
    FEMENINO = 'F'
    MASCULINO = 'M'
    STATE_CHOICES = [
        (FEMENINO, 'Femenino'),
        (MASCULINO, 'Masculino'),
    ]
    #alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    rut = models.IntegerField(unique=True)
    dv = models.CharField(max_length=1, blank=True, null=True)
    genero = models.CharField(max_length=1, choices=STATE_CHOICES, null=True)
    nombres = models.CharField(max_length=255, blank=True, null=True)
    apellido_paterno = models.CharField(max_length=255, blank=True, null=True)
    apellido_materno = models.CharField(max_length=255, blank=True, null=True)
    nombre_apoderado = models.CharField(max_length=255, blank=True, null=True)
    domicilio_actual = models.CharField(max_length=255, blank=True, null=True)
    Comuna_residencia = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    telefono = models.CharField(max_length=255, blank=True, null=True)
    celular = models.CharField(max_length=255, blank=True, null=True)
    fecha_nacimiento = models.DateField(auto_now=False, blank=True, null=True)
    codigo_etnia = models.IntegerField(blank=True, null=True)
    #Matricula comienza aqui
    establecimiento = models.ForeignKey(
        Establecimiento, 
        on_delete=models.CASCADE,
        to_field='rbd'
    )
    nivel = models.CharField(max_length=255, blank=True, null=True)
    letra = models.CharField(max_length=6, blank=True, null=True)
    año = models.CharField(max_length=4, blank=True, null=True)
    fecha_incorporacion = models.DateField(auto_now=False, blank=True, null=True)
    fecha_retiro = models.DateField(auto_now=False, blank=True, null=True)

    esta_activo = models.BooleanField()

    def __str__(self) -> str:
        return f'{self.nombres} {self.apellido_paterno} {self.apellido_materno} {self.nivel} - {self.letra}'
    
    def get_absolute_url(self):
        return reverse('matricula_detail', args=[str(self.id)])

    def clean(self):
        # Asegurarse que el establecimiento_id sea el ID y no el RBD
        if self.establecimiento_id and str(self.establecimiento_id) == self.establecimiento.rbd:
            self.establecimiento_id = self.establecimiento.id



class FuncionarioEstablecimiento(models.Model):
    rut = models.IntegerField(unique=True)
    dv = models.CharField(max_length=1)
    nombre = models.CharField(max_length=255)
    apellido_paterno = models.CharField(max_length=255)
    apellido_materno = models.CharField(max_length=255)
    cargo = models.CharField(max_length=255)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    direccion = models.CharField(max_length=255, null=True, blank=True)
    
    establecimiento = models.ForeignKey(Establecimiento, on_delete=models.CASCADE)

    class Meta:
        db_table = 'funcionario'
        verbose_name = "funcionario"
        verbose_name_plural = "funcionarios"

    def __str__(self) -> str:
        return f'{self.nombre} {self.apellido_paterno} {self.apellido_materno}'
    

    def get_absolute_url(self):
        return reverse('funcionario_detail', args=[str(self.id)])


class Mail(models.Model):
    email = models.EmailField()

    def __str__(self) -> str:
        return f'{self.email}'
    
    class Meta:
        db_table = 'email'
        ordering = ['-id']
        verbose_name = "email"
        verbose_name_plural = "correos"

    


class CorreosEstablecimiento(models.Model):
    establecimiento = models.ForeignKey(Establecimiento, on_delete=models.CASCADE)
    lista_mails = models.ManyToManyField(Mail)

    def __str__(self) -> str:
        correos = ', '.join(str(v) for v in self.lista_mails.all())
        return f'{self.establecimiento} : {correos}'
    
    class Meta:
        db_table = 'correos_establecimiento'
        ordering = ['-id']
        verbose_name = "correo establecimiento"
        verbose_name_plural = "correos por establecimientos"


class Alerta(models.Model):
    envio_correos_establecimiento = models.ForeignKey(CorreosEstablecimiento, on_delete=models.CASCADE)
    cuerpo_mensaje = models.TextField()

    def __str__(self) -> str:
        return f'{self.envio_correos_establecimiento} : {self.cuerpo_mensaje}'
    
    class Meta:
        db_table = 'alerta'
        ordering = ['-id']
        verbose_name = "alerta rapida"
        verbose_name_plural = "alertas"


class CasoVulneracion(models.Model):
    ONGOING = 'ong'
    NOLEIDO = 'nol'
    FINSH = 'fin'
    STATE_CHOICES = [
        (NOLEIDO, 'No leido'),
        (ONGOING, 'En revisión'),
        (FINSH, 'Finalizado'),
    ]
    fecha_creacion = models.DateField()
    estado = models.CharField(max_length=255, choices=STATE_CHOICES, default=NOLEIDO)

    def __str__(self) -> str:
        return f'{self.pk} - {self.fecha_creacion}'

    
    class Meta:
        db_table = 'caso_vulneracion'
        ordering = ['-id']
        verbose_name = "Caso Vulneracion"
        verbose_name_plural = "Casos vulneraciones"
    

    def get_absolute_url(self):
        return reverse('discriminacion_detail', args=[str(self.id)])



class Discriminacion(models.Model):
    ONGOING = 'ong'
    NOLEIDO = 'nol'
    FINSH = 'fin'
    STATE_CHOICES = [
        (NOLEIDO, 'No leido'),
        (ONGOING, 'En revisión'),
        (FINSH, 'Finalizado'),
    ]
    fecha_creacion = models.DateField()
    estado = models.CharField(max_length=255, choices=STATE_CHOICES, default=NOLEIDO)

    CARAC_FIS_PER = 'cfp'
    DISC_DIS_INT = 'ddi'
    EMBARAZO_MODERNIDAD = 'em'
    IDENT_GEN = 'ig'
    OPC_RELIG = 'opc'
    ORIEN_SEXUAL = 'os'
    PROBL_SALUD = 'ps'
    MIGRA_RAC = 'mr'
    SDA = 'sda'

    STATE_CHOICES = [
        (CARAC_FIS_PER, 'Características físicas y/o personales'),
        (DISC_DIS_INT, 'Discapacidad física y/o intelectual'),
        (EMBARAZO_MODERNIDAD, 'Embarazo y Maternidad'),
        (IDENT_GEN, 'Identidad de género'),
        (OPC_RELIG, 'Opción religiosa'),
        (ORIEN_SEXUAL, 'Orientación Sexual'),
        (PROBL_SALUD, 'Problemas de Salud'),
        (MIGRA_RAC, 'Ser migrante u origen racial'),
        (SDA, 'Síndrome de déficit atencional'),
    ]

    tipo_discrim = models.CharField(max_length=255, choices=STATE_CHOICES, default=CARAC_FIS_PER)
    victima = models.ForeignKey(Matricula, on_delete=models.CASCADE, related_name='victima', null=True)
    agresor = models.ForeignKey(Matricula, on_delete=models.CASCADE, related_name='agresor', null=True)
    detalle = models.CharField(max_length=255, null=True)

    def __str__(self) -> str:
        return f'{self.pk} - {self.detalle}'

    def get_absolute_url(self):
        return reverse('discriminacion_detail', args=[str(self.id)])

    class Meta:
        db_table = 'discriminacion'
        ordering = ['-id']
        verbose_name = "discriminacion"
        verbose_name_plural = "discriminaciones"



class MedidasDiscriminacion(models.Model):
    caso = models.ForeignKey(Discriminacion, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Caso Discriminacion")
    condicionalidad = models.BooleanField()
    devolucion_casa = models.BooleanField()
    expulsion = models.BooleanField()
    suspension_clases = models.BooleanField()
    descripcion_de_medidas = models.CharField(max_length=255)

    class Meta:
        db_table = 'medidas'
        ordering = ['-id']
        verbose_name = "medida discriminacion"
        verbose_name_plural = "medidas discriminacion"

    def __str__(self):
        return f'{self.id} - {self.descripcion_de_medidas}'



class CasoFaltaAConvivencia(models.Model):
    ONGOING = 'ong'
    NOLEIDO = 'nol'
    FINSH = 'fin'
    STATE_CHOICES = [
        (NOLEIDO, 'No leido'),
        (ONGOING, 'En revision'),

templates/maltrato/create_case.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Maltrato{% endblock title %}
{% block fullcard %}
{% block head %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/js/standalone/selectize.min.js"
    integrity="sha512-pF+DNRwavWMukUv/LyzDyDMn8U2uvqYQdJN0Zvilr6DDo/56xPDZdDoyPDYZRSL4aOKO/FGKXTpzDyQJ8je8Qw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.3/css/selectize.bootstrap4.min.css"
    integrity="sha512-MMojOrCQrqLg4Iarid2YMYyZ7pzjPeXKRvhW9nZqLo6kPBBTuvNET9DBVWptAo/Q20Fy11EIHM5ig4WlIrJfQw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

{% endblock head %}
<div class="card">
    <div class="card-header">
        <div class="row d-flex">
            <div class="col-sm-6">
                <h1 class="display-6">Crear Caso Maltrato</h1>
            </div>
        </div>
        
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <form action="" method="post">
                        {% csrf_token %}
                        <label for="fecha">Fecha del Suceso</label>
                        {{form.fecha_creacion}}

                        <label for="fecha">Tipo de Maltrato</label>
                        {{form.tipo_maltrato}}

                        <div class="relacion-funcionario-alumno">
                            <label for="funcionario">Funcionario Agresor</label>
                            {{form.funcionario_agresor}}

                            <label for="victima">Victima</label>
                            {{form.victima}}

                        </div>


                        <label for="victima">Detalle</label>
                        {{form.detalle}}
                        <br>

                        <button type="submit" class="btn btn-success">Crear</button>
                    </form>




                </div>

            </div>
        </div>
        <form action="" method="POST">

            {% csrf_token %}
            <br />
            {{form.as_p}}
            <table>

            </table>
            <button type="submit" class="btn btn-success">Crear</button>
        </form>
    </div>
</div>

<script>
    $(function () {
        $("#id_victima").selectize({
            sortField: 'text',
        });
        $("#id_tipo_maltrato").selectize({
            sortField: 'text',
        });
    });

    $('#id_tipo_maltrato').change(function () {
        console.log("Javascript culiaos");
        console.log(this.value)

        let seleccion = this.value;

        
        switch (seleccion) {
            case 'adulto':
                console.log("Adulto Agrede a Estudiante");
                break;
            case 'estudiante':
                console.log("Estudiante Agrede a Estudiante");
                break;
            case 'alumno_docente':
                console.log("Alumno  Agrede a Docente o  Funcionario");
                $('#id_victima')
                break;
        }

    })
</script>

{% endblock fullcard %}

templates/maltrato/create_case_adulto_adulto.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Maltrato{% endblock title %}
{% block head %}
<link rel="stylesheet" href="{% static 'lib/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

<script src="{% static 'lib/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'lib/plugins/select2/js/i18n/es.js' %}"></script>

{% endblock head %}
{% block fullcard %}
<div class="card">
    <div class="card-header">
        <div class="row d-flex">
            <div class="col-sm-12">
                <h1 class="display-6">Crear Caso Maltrato Adulto a Adulto</h1>
            </div>
        </div>
        <h1 style="color: red;"> ALERTA: Este tipo de situaciones podrían ser catalogadas como delito, por lo tanto, debe ser gestionado por el(la) director(a).
        </h1>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        
        <button type="submit" class="btn btn-success">Crear</button>
    </form>
</div>
<script>
    $(function () {
        //Initialize Select2 Elements
        $('#id_victima').select2({
            language: "es",
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('#id_alumno_agresor').select2({
            language: "es",
            theme: 'bootstrap4'
        })
    })
</script>
{% endblock fullcard %}

templates/maltrato/create_case_adulto_menor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Maltrato{% endblock title %}
{% block head %}
<link rel="stylesheet" href="{% static 'lib/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

<script src="{% static 'lib/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'lib/plugins/select2/js/i18n/es.js' %}"></script>

{% endblock head %}
{% block fullcard %}
<div class="card">
    <div class="card-header">
        <div class="row d-flex">
            <div class="col-sm-12">
                <h1 class="display-6">Crear Caso Maltrato Adulto a Menor</h1>
            </div>
        </div>
        <h1 style="color: red;"> ALERTA: Este tipo de situaciones podrían ser catalogadas como delito, por lo tanto, debe ser gestionado por el(la) director(a).
        </h1>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        
        <button type="submit" class="btn btn-success">Crear</button>
    </form>
</div>
<script>
    $(function () {
        //Initialize Select2 Elements
        $('#id_victima').select2({
            language: "es",
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('#id_alumno_agresor').select2({
            language: "es",
            theme: 'bootstrap4'
        })
    })
</script>
{% endblock fullcard %}

templates/maltrato/create_case_alumno_alumno.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Maltrato{% endblock title %}
{% block head %}
<link rel="stylesheet" href="{% static 'lib/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'lib/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

<script src="{% static 'lib/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'lib/plugins/select2/js/i18n/es.js' %}"></script>

{% endblock head %}
{% block fullcard %}
<div class="card">
    <div class="card-header">
        <div class="row d-flex">
            <div class="col-sm-12">
                <h1 class="display-6">Crear Caso Maltrato Menor a Menor</h1>
            </div>
        </div>
        <h1 style="color: red;"> ALERTA: Este tipo de situaciones podrían ser catalogadas como delito, por lo tanto, debe ser gestionado por el(la) director(a).
        </h1>
    </div>
</div>
<div class="card">
    <div class="card-body">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        
        <button type="submit" class="btn btn-success">Crear</button>
    </form>
</div>
<script>
    $(function () {
        //Initialize Select2 Elements
        $('#id_victima').select2({
            language: "es",
            theme: 'bootstrap4'
        })

        //Initialize Select2 Elements
        $('#id_alumno_agresor').select2({
            language: "es",
            theme: 'bootstrap4'
        })
    })
</script>
{% endblock fullcard %}

templates/maltrato/list.html
<td>{{ caso.get_afectado }}</td> 

templates/maltrato/update_case.html
{% extends 'base.html' %}
{% block title %}Cambiar Estado Caso Maltrato  {% endblock title %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row">
                <div for="{{ field.label }}" class="col-sm-2 col-form-label">
                    {{ field.label_tag }}
                </div>
                <div class="col-sm-10">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Actualizar</button>
        </form>
    </div>

    <div class="col-sm-12 mt-5">
        <div class="form-group border-bottom row">
            <label for="" class="col">
                Información Victima
            </label>
            <div class="col">
                <strong>{{object.victima}}</strong>
            </div>
        </div>

        <div class="form-group border-bottom row">
            <label for="" class="col">
                Estado actual del caso
            </label>
            <div class="col">
                {{object.get_estado_display}}
            </div>
        </div>

        <div class="form-group border-bottom row">
            <label for="" class="col">
                Fecha del Caso
            </label>
            <div class="col">
                {{object.fecha_creacion}}
            </div>
        </div>

        <div class="form-group border-bottom row">
            <label for="" class="col">
                Detalle de lo sucedido
            </label>
            <div class="col">
                {{object.detalle}}
            </div>
        </div>
    </div>
</div>

{% endblock content %}